name = input("Enter your name = ")
age = input("Enter your age = ")
mothers_name = input("Enter mothers name = ")
mothers_age = input("Enter mothers age = ")
fathers_name = input("Enter fathers name = ")
fathers_age = input("Enter fathers age = ")
grandmas_name = input("Enter grandmas name = ")
grandmas_age = input("Enter grandmas age = ")
brothers_name = input("Enter brothers name = ")
brothers_age = input("Enter brothers age = ")

print(" ")
print("your name: " + name + " and " + "your age: " + age)
print("mothers name: " + mothers_name + " and " + "mothers age: " + mothers_age)
print("fathers name: " + fathers_name + " and " + "fathers age: " + fathers_age)
print("grandmas name: " + grandmas_name + " and " + "grandmas age: " + grandmas_age)
print("brothers name: " + brothers_name + " and " + "brothers age: " + brothers_age)